### ISSUE TITLE
NotIn QuerySet function

### ISSUE THREAD

**Issue by grechkin-pogrebnyakov** [jirfag/go-queryset#12]
this function
`StatusNotIn(status types.TXStatus, statusRest ...types.TXStatus)`

has to be used like this:
`StatusNotIn(types.CompletedTXStatuses[0], types.CompletedTXStatuses[1:]...)`

as for me, better way is
`StatusNotIn(types.CompletedTXStatuses...)`

**Comment by jqs7** [comment]
Same as the `xxxIn()` functions

**Comment by jqs7** [comment]
what's the purpose of the first argument in InMethod? 

if there's no spicial purpose, could I take a [pull request](https://github.com/jqs7/go-queryset/commit/3de32f012a022ffeda30a167376f0fcadc8cd078) to close this issue?

**Comment by derElektrobesen** [comment]
First argument is required to be sure there is at least one argument passed in the function.

Previously each method was checked by Compiler that the arguments list is not empty and sql query is valid. Now this check is not works.

Yes, this limitation makes the interface less beautiful, but go-queryset is positioned as "Safe for use" and this is OK.

**Comment by derElektrobesen** [comment]
You could try to make "unsafe" versions of this function. Where user understands he must check the list of elements before call. Or try to add an error into the query and decline request invocation with this error.

But I think it is not necessary.

**Comment by grechkin-pogrebnyakov** [comment]
You could save information about empty list error in queryBuilder object and return error after call of execution

**Comment by derElektrobesen** [comment]
No, commonly users are too lazy to check the array length =)

I'm not sure this enhancement is really needed.
I think current interface is OK and its positive sides neutralize inconveniences.

**Comment by jqs7** [comment]
Just because users are lazy, so we warp the error check in the function. 😄

**Comment by jirfag** [comment]
@jqs7 @derElektrobesen @grechkin-pogrebnyakov thank you!
I like the idea of error saving if `len(args) == 0` and returning then. Pull requests are welcome, I can do it myself in 1-3 weeks.

**Comment by jqs7** [comment]
Cool !!! @jirfag 
how about:
```
func (qs UserQuerySet) IDIn(ID ...uint) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}
```
if the code above is ok, i'll make a pull request right now 😋
