### ISSUE TITLE
can't generate query sets on Windows

### ISSUE THREAD

**Issue by JermineHu** [jirfag/go-queryset#18]
**My ENV: 
 `go version go1.9.2 windows/amd64`**

**My Code Path:**

`E:\GOPATH\src\test\models.go`

 **My question :** 
To excute `go  generate ./... `  got a failure info :  can't generate query sets: can't parse file models.go to get structs: can't load types for file models.go in package "./."       **But in Desktop dictionary path “test/models.go” to excute `go  generate ./... `  was successful !**  

**The code :**

```
import "github.com/jinzhu/gorm"

//go:generate goqueryset -in models.go
// User struct represent user model. Next line (gen:qs) is needed to autogenerate UserQuerySet.
// gen:qs
type User struct {
	gorm.Model
	Rating      int
	RatingMarks int
}
```

**Comment by ARowden** [comment]
I'm also having this issue.

**Comment by lightglitch** [comment]
I'm having something similar and I think 

https://github.com/jirfag/go-queryset/blob/master/parser/parser.go#L46

windows paths, I will try to do some debugging.

**Comment by jirfag** [comment]
I merged [PR](https://github.com/jirfag/go-queryset/pull/22) from @lightglitch 
@JermineHu @ARowden @lightglitch please check issue on master branch
