### ISSUE TITLE
check if table exists ?

### ISSUE THREAD

**Issue by joeblew99** [jirfag/go-queryset#2]
Just trying this out.. Its pretty nice..
i dont think the generated code checks if the Table exists ?

What do you think about the idea of being able to generate the check and for all functions to call it ?
It would be a flag on the generator, so you dont have to use it.

Its very nice at Development time to more fast.

--

It brings uo the whole question of migrations of course too....

**Comment by jirfag** [comment]
Hello!
1. What to do if we've found, that table doesnt exist? Return special error? Panic? Something else?
I suggest next autogenerated tables manager for struct `User`:
```go
type UserTableManager struct {
  db *gorm.DB
}

func NewUserTableManager(db *gorm.DB)UserTableManager  {}

func (m UserTableManager) CreateTable() error {}
func (m UserTableManager) DropTable() error {}
func (m UserTableManager) AddColumn(...) error {}
func (m UserTableManager) DropColumn(...) error {}
// etc
```
2. I can support automigrations with this tables manager:
```go
func (m UserTableManager) AutoMigrate() error {}
```

What do you think about that?
