### ISSUE TITLE
The method `Update` can only be used inside a package.

### ISSUE THREAD

**Issue by vadimlarionov** [jirfag/go-queryset#29]
From your examples:
```go
// Update updates User fields by primary key
func (o *User) Update(db *gorm.DB, fields ...userDBSchemaField) error {
	...
}
```
Method `Update`  receives arguments of type `userDBSchemaField` (unexported), but method is exported. I propose rename type `userDBSchemaField` from unexported type to exported.

**Comment by jirfag** [comment]
merged fix, thank you
