### ISSUE TITLE
Missing packages on generate

### ISSUE THREAD

**Issue by iain17** [jirfag/go-queryset#3]
When I run ```go generate ./...``` using the latest master code. I get a file called autogenerated_***.go just like the readme states it should. The problem is that it is importing a package called base "github.com/jirfag/go-queryset/queryset/base" which doesn't seem to exist.

It also misses the packages "time" and "fmt"

Any ideas?

**Comment by iain17** [comment]
Found the perpetrator: https://github.com/jirfag/go-queryset/blob/8c5bf5e54ab85a93af43982021138de95eb46230/queryset/bootstrap.go#L58

I'm just wondering why these packages?

**Comment by jirfag** [comment]
Thank you for this report!
Just fixed bad import of `github.com/jirfag/go-queryset/queryset/base`. It worked for me because `goimports` siliently removed it.

I've fixed bad import in `master` branch.
Also I will try to fix missing `goimports`, using it from vendor.

**Comment by jirfag** [comment]
Now goimports isn't needed: we use goimports source code and call it directly
