### ISSUE TITLE
vgo/go mod support

### ISSUE THREAD

**Issue by Azuka** [jirfag/go-queryset#44]
Thanks for this great package. I noticed that since I moved my project to go modules, the generation stopped working.

The issue appears to be with packages created outside the `$GOPATH`. Is there planned support for this?

**Comment by jonathaningram** [comment]
@jirfag is this something you'd consider receiving a PR for? Our project is currently unable to reliably use goqueryset with recent version of Go that use modules. I posted in the Gophers slack channel and was pointed in the direction of a solution. My question: https://gophers.slack.com/archives/C0VPK4Z5E/p1551421718097300

The recommended solution:

> you need to be using https://godoc.org/golang.org/x/tools/go/packages

> `golang.org/x/tools/go/packages` is the modules-aware replacement for `go/build` and `golang.org/x/tools/go/loader`

**Comment by jirfag** [comment]
hi!
Sorry for the slow response. I've refactored the project in the pull request https://github.com/jirfag/go-queryset/pull/45:
  - use go/packages for packages loading (it support go modules)
  - use go modules instead of dep
  - other improvements

Please, check does it work for you case.

**Comment by Azuka** [comment]
Thanks @jirfag, this works now.
