### ISSUE TITLE
Interesting Generation Error

### ISSUE THREAD

**Issue by chrisfentiman** [jirfag/go-queryset#5]
First off, awesome job on this package, I was really impressed with the api it generated so much so we started migrating our GORM queries across to use this package instead.

So the issue is I have an Enum that is imported from another package. This seems to work fine on other code generations we have. However, when I generated code using go-queryset I got an unexpected result.

The struct `// gen:qs` is above looks like this:
```
type Example struct {

	PriceID int64

	Currency forex.Currency

        ....
}
```

The Generated code for currency looks like this:
```
// CurrencyEq is an autogenerated method
// nolint: dupl
func (qs ExampleQuerySet) CurrencyEq(currency v1.Currency) ExampleQuerySet {
	return qs.w(qs.db.Where("currency = ?", currency))
}

// CurrencyGt is an autogenerated method
// nolint: dupl
func (qs ExampleQuerySet) CurrencyGt(currency v1.Currency) ExampleQuerySet {
	return qs.w(qs.db.Where("currency > ?", currency))
}

....
```

The error is that the generated code has placed `v1` as the package selector and not the actual package name `forex`. 

This is non-blocking for me as It's very easy to fix up manually. However, this would suggest that the code generation is picking up v1 from the file path? The import is like so: `import "go.company.com/internal-files/companyapi/forex/v1"`.

Happy to help look into this problem but I thought I'd raise it first just in case something like this has occurred else where.

**Comment by jirfag** [comment]
Hello!
Thank you for report, I will look at it in 24 and try to fix it ASAP

**Comment by jirfag** [comment]
Fixed bug in master, check it please

**Comment by chrisfentiman** [comment]
Works perfectly. Thanks!
