### ISSUE TITLE
Cannot generate code

### ISSUE THREAD

**Issue by Nokel81** [jirfag/go-queryset#50]
I have installed `goqueryset` which looks something like the following:

```
// go:generate goqueryset -in types.go

// gen:qs
type Object struct {
	ID                 id.TargetID `gorm:"PRIMARY_KEY"`
	LastSeen           *LastSeen   `gorm:"foreignkey:TargetID"`
	RegistrationStatus database.RegistrationStatus
	RegistrationToken  string `gorm:"UNIQUE"`
}

// gen:qs
type LastSeen struct {
	TargetID id.TargetID
	Time     time.Time
}
```

However, if I run the following `go generate` in the same folder that file is, I get an exit code of `0` and no file

**Comment by derElektrobesen** [comment]
The problem is with `go:generate`, not with goqueryset.

Just remove the space symbol before `go:generate` and it will work.
