### ISSUE TITLE
Missing Private Fields

### ISSUE THREAD

**Issue by Nokel81** [jirfag/go-queryset#51]
This system is excellent. However, all private fields are ignored. This is probably a good decision in general but I think that if the gorm struct tag `Column` is present then even private fields should be generated for.

**Comment by derElektrobesen** [comment]
Golang not accepts writings into the private structures fields.

We can't implement this feature, sorry.

https://yourbasic.org/golang/access-private-field-reflection/

**Comment by Nokel81** [comment]
Thanks for the quick response. However, it doesn't look like any of the generated code uses `reflect`. So I must assume that you use it internally.

**Comment by derElektrobesen** [comment]
Gorm uses reflection under the hood.
