### ISSUE TITLE
how to use with transactions

### ISSUE THREAD

**Issue by leiohpvgmf24aac9** [jirfag/go-queryset#57]
how to use queryset with transactions? a example would be good

https://gorm.io/docs/transactions.html

**Comment by derElektrobesen** [comment]
Each queryset takes `*gorm.DB` as argument. Just start the transaction and pass new instance of gorm.DB into queryset constructor.

```go
db := gorm.Open(/* ... */)
tx := db.Begin()
defer tx.Commit()

q := NewSomeQuerySet(db) // use `q` to query database
```
